### ISSUE TITLE
Connecting Gridlock to Re:mix

### ISSUE THREAD

**Issue by ZKoster** [el-quinto/mix#10]
Hey el-quinto,
I'm just trying to figure out how to connect Gridlock to Re:mix, I'm not sure if you need to have a prefix or not for them to communicate together, I'm fairly certain my monome emulation with my LaunchPad is set up with Gridlock in the right way, I'm just not sure how them link up together.
Thanks heaps,
Zac Koster.

**Comment by el-quinto** [comment]
there's a secondary serialosc.maxpat u'll need to install for gridlock, check out the zeroconf folder. also, you'll need to enable the zeroconf switch in the setup tab.

**Comment by ZKoster** [comment]
Ahh right, what directory should the serialosc.maxpat be in for gridlock? I'm running Live 9 with Max 7 and just can't quite figure it out.
Thanks again dude

**Comment by ZKoster** [comment]
Alright, I've connected up the serialosc correctly, set my Launchpad as a 64 Monome through Gridlock, all the top row controls work perfect, but can't get the actual sample to play. It isn't getting any send/recieve messages on Gridlock except for those top row controls.
Cheers!

**Comment by ZKoster** [comment]
Had to push play ;)
Thanks heaps for your help man!
Koster
