### ISSUE TITLE
Crash on macOS 10.13.6 and Live Suite 10.1

### ISSUE THREAD

**Issue by brackindustries** [el-quinto/mix#13]
Upon dragging the re[mix] onto a midi track, I am asked to install the legacy version of Java SE 6 Runtime, and Ableton crashes with EXC_BAD_ACCESS (SIGSEGV). Is there any chance to get this running in a more-or-less 2019 environment?

**Comment by herringson** [comment]
I'm using Live 10.1 and despite getting a Java warning re:mix loads, I've used it for some time without Java installed at all but haven't tested in lately.  I _think_ Java is only used for some of the API/send control stuff that I don't use.

Is Live using the bundled version of Max or are you pointing Live at an older version of Max?
You can check this in Live's preferences under the File/Folder tab.

I'm using 10.1 release version and the included/bundled Max version.

![Screenshot 2019-06-12 at 09 58 47](https://user-images.githubusercontent.com/648631/59309954-0d560f80-8cf9-11e9-841c-4311bdb6d890.png)

**Comment by newmodernscience** [comment]
i'm using Live 10.1, Java 8.211, Max 8. Works fine here.





*Chris Hahn*
Creative Specialist \ Digital Artist
503.999.4739 (c)

web <http://newmodernscience.com> | about.me
<http://about.me/christopherhahn> | facebook
<http://www.facebook.com/ChristopherHahn> | twitter
<http://twitter.com/chrishahn>  | youtube
<http://www.youtube.com/user/newmodernscience> | vimeo
<https://vimeo.com/chrishahn>

**Comment by brackindustries** [comment]
Well... I tried updating Java 8 to the latest version and uninstalling it completely, same symptom. Must be some special issue with my setup... :(
I use the bundled version of Max 8, by the way. And my hardware is a 2012 MBP, which has been a pretty stable machine so far.
Thanks for your support!

**Comment by brackindustries** [comment]
Made it work like this: Install smelly Java 6 SE Runtime from Apple website as suggested by the pop up message, update to latest Java (8.211) from java.com website: No more crashes. Thank you all, case closed (I only wished I could go along without Java and I hope I do not have any giant security holes in my system now...).

**Comment by herringson** [comment]
From memory Java is only used in one part of the patch and it's to do with the Live API/LOM remote control of sends or something.  I opened that patch up, found the one place the java object was used and deleted it to remove the Java dependency.

It must break some of the send control functionality but I don't use this at all, I just use the main sampling workflow stuff and removing Java doesn't seem to effect that.
