### ISSUE TITLE
black window

### ISSUE THREAD

**Issue by Hiko-Tanizawa** [el-quinto/mix#2]
Thank you for the new version and new name.:)
I'm really happy that you use new name.:)
thank you again.

There was black window appear ,When i opened it .

![screen shot 2015-02-19 at 10 18 25 pm](https://cloud.githubusercontent.com/assets/11038409/6282177/576a8346-b885-11e4-852f-0763bd67908d.png)

**Comment by el-quinto** [comment]
hmmm, i was hoping if i had all the files in one folder i wouldn't have to freeze the devices every time. (it's working for me for some reason)

i'll freeze the devices again and re-upload.
