### ISSUE TITLE
clicking sound when press top row 13&14 to go through presets

### ISSUE THREAD

**Issue by Hiko-Tanizawa** [el-quinto/mix#3]
Hi There is clicking noise when press top row 13&14 and this slows down tempo when press it fast.

**Comment by Hiko-Tanizawa** [comment]
send mode occurs after sample window catch up presets.
When i change lot of presets,sample is following in sample window but then send is only happens after window catch up preset.
(sorry for my english..)

**Comment by Hiko-Tanizawa** [comment]
I made video.:)
https://www.dropbox.com/s/yi5bxyfmvj4c82y/ScreenFlow.mp4?dl=0

**Comment by el-quinto** [comment]
i removed the object that prevented clicking when changing presets because i thought i didn't need it anymore. i wasn't getting clicks, but i didn't test it much. i just added it back in. let me know if it fixes it.

**Comment by Hiko-Tanizawa** [comment]
No more clicks.:)
but still has send issue.

**Comment by el-quinto** [comment]
is the name in the sample window still lagging behind?

**Comment by Hiko-Tanizawa** [comment]
Just little bit.
it's way faster than before and I think it's fine because I don't think people don't use send with go thru presets like crazy.lol

found similar issue with volume fader .
sometimes there is lag with volume fader ,and send occur after lag.

**Comment by el-quinto** [comment]
i'm assuming this happens because of task priority. the preset changes are still processing so the send change is going to occur in order (once the previous task completes). same with volume- if the volume changes are still processing (lagging behind) it'll have the same issue. i don't think there's anything i can do about the volume. (i think it's as good as it'll get), but i'll look into optimizing the row/detail coding and make it lag less.

**Comment by Hiko-Tanizawa** [comment]
Thank you :)
I see, i understood.
It's not big lag when i tap buttons instead of holding down to control volumes.

**Comment by el-quinto** [comment]
btw if u want to try loading different sets without having to delete the device, i've made some changes that should make that possible.

**Comment by Hiko-Tanizawa** [comment]
Yes, it works fine.
i opened 3 different sets and no problem.:)

**Comment by el-quinto** [comment]
i made some optimizations to the preset changes. plz let me know if it seems faster, or if u get clicking sounds again.

**Comment by Hiko-Tanizawa** [comment]
Sorry for late.
Yes it's faster and no click sound.:)

**Comment by Hiko-Tanizawa** [comment]
Can you check zeroconfig version work with another controller or monome?
I can't connect with my push this time with gridlock and it won't greyed out when i click zeroconfig button.

**Comment by el-quinto** [comment]
just re-uploaded. i'm using a new way of loading the alternate serialosc.maxpat now. see the zeroconf folder

**Comment by Hiko-Tanizawa** [comment]
Thank you.
I'm not sure if i use it wrong way , but i can not connect with gridlock with this version.

**Comment by Hiko-Tanizawa** [comment]
It's greyed out now when i click zeroconfig,but i can't get prefix  and serialosc ID from gridlock.

**Comment by Hiko-Tanizawa** [comment]
I'm sorry .
I found out :)
I can connect it with gridlock clicking VserialOSC :)
thank you very much:)

**Comment by Hiko-Tanizawa** [comment]
Also thank you for fixing volume fader.
it's so smooth:)

**Comment by el-quinto** [comment]
yes, the gridlock one doesn't use zeroconf, so it can be used in 64-bit. i'll rename the gridlock folder to gridlock-vserialosc so people will know.
