### ISSUE TITLE
Samples won't play.

### ISSUE THREAD

**Issue by Hiko-Tanizawa** [el-quinto/mix#5]
I found a bag .
when I drag samples onto the row from browser ,it won't play correctly or won't play at all.
All i did was changing sample start/end point and added another samples from browser.
Did you change way to save re[mix] set? it's happens with my set .
it's not happen with blank new set.

**Comment by el-quinto** [comment]
no, i haven't changed anything with the presets. (or saving a set)

for the samples that won't play correctly/or at all, if u double click the waveform (to select all), does it play correctly then?

**Comment by Hiko-Tanizawa** [comment]
here's link for video .
https://www.dropbox.com/s/e9pozkjy18kc89z/sample%20bug2.mp4?dl=0

**Comment by Hiko-Tanizawa** [comment]
"for the samples that won't play correctly/or at all, if u double click the waveform (to select all), does it play correctly then?"

I just tried it but waveform was correct this time but no sound.

**Comment by Hiko-Tanizawa** [comment]
I just use Save+write all to folder and load it from there then works fine.
it's weird.

**Comment by el-quinto** [comment]
very weird. does this happen with any samples? or just the ones in the dj krush folder?

**Comment by Hiko-Tanizawa** [comment]
this happens with any samples.
I will use duplicated one for now:)
but someone may report this future.

**Comment by el-quinto** [comment]
this is tough…

could you dropbox me a copy of your preset and flist file for the original set? that might help.

**Comment by Hiko-Tanizawa** [comment]
do you need one from original or duplicated one?

**Comment by Hiko-Tanizawa** [comment]
This one?
https://www.dropbox.com/sh/j6utbfbimkv9tzd/AAC9AyMSZorrOQVh2g0kw1Fca?dl=0

**Comment by el-quinto** [comment]
thx. i guess if you could send me the same files for the duplicated one, it would help me figure out why one has this problem and the other doesn't.

**Comment by Hiko-Tanizawa** [comment]
I just found out that No waveform appear but it keeps in the drop down place ,When I add sample to blank slot with that set.

**Comment by Hiko-Tanizawa** [comment]
I opened old version of re:[mix].
(it was still called redux from 2/1 2015 .)

this version works fine.

**Comment by Hiko-Tanizawa** [comment]
Duplicated one.
File name is different ..I didn't name it.
https://www.dropbox.com/sh/77i9n2ix2e2aqkw/AAAQ5KXM5LpBy7V_f6cFSYTva?dl=0

**Comment by el-quinto** [comment]
thx. i looked at the flist files and everything looks the same except the folder names, which is good. the preset files are identical, which is also good. i'll need to think about this over the weekend. i'll report back.

**Comment by Hiko-Tanizawa** [comment]
You're welcome .:)
I guess something changed by accident?
there is no this issue with Redux from 2/1/2015.

**Comment by el-quinto** [comment]
one more thing u could try-

with the original set, if u drag a sample from the desktop to a row, does it still have this issue? i think the way u name your folders might be related. maybe not, but i just want to be sure.

**Comment by el-quinto** [comment]
a lot has changed since 2/1 so it would be hard to say what it might be...

**Comment by el-quinto** [comment]
could u try this version and let me know if it still happens
https://dl.dropboxusercontent.com/u/35035949/re%5Bmix%5D.amxd.zip

whenever convenient. no rush.

**Comment by Hiko-Tanizawa** [comment]
It's still happen.
it won't play sample..

**Comment by el-quinto** [comment]
ok try this build. (no fixes here. i just made a certain object print to the max window for debugging) https://dl.dropboxusercontent.com/u/35035949/re%5Bmix%5D.amxd.zip

when u add a sample and it doesn't play correctly, i need u to open the max window and take a screenshot of the most recent entries. also go to the setup tab, double-click 'coll [mlr]ch 1' and take a screenshot of the window that pops up. this will help a lot.

**Comment by Hiko-Tanizawa** [comment]
How can i open max window over Ableton?
I clicked "m" button but noting appear.

**Comment by Hiko-Tanizawa** [comment]
I dragged samples from desktop but it won't play either.

**Comment by Hiko-Tanizawa** [comment]
I found pattern .
"example"
when I drop sample A on 2nd row ,it won't play then drop sample B on 3rd row ,B will play on 2nd row,then drop C on 4th row,C will play on 3rd row and so on..

**Comment by Hiko-Tanizawa** [comment]
Is there way to open max window?
cmd+m does midi mapping in ableton.

**Comment by Hiko-Tanizawa** [comment]
Never mind .
I can go to max window by clicking max editor button but then I can't even play loaded samples.
I think presentation version takes over actions.

**Comment by Hiko-Tanizawa** [comment]
Sorry for posting many times.
I was able to load my set in max (presentation version) but i can't play any sound.
"1[mlr]pl-trig: no such object" appear with pink color.

https://www.dropbox.com/sh/2weesgxn3m30aqe/AABvzrznA7PG0qB3o8Mq9bOia?dl=0

I hope this one helps..

**Comment by el-quinto** [comment]
ahh sorry. to open the max window, right click on the top of the device. (where it says re[mix]).
https://dl.dropboxusercontent.com/u/35035949/Screen%20Shot%202015-03-13%20at%203.58.15%20PM.png

no need to open the editor. no need to click the m button either.

**Comment by el-quinto** [comment]
when u take the screenshot of the max window again, make sure you expand the window so i can see the whole entry.

**Comment by Hiko-Tanizawa** [comment]
Thanks .
I learn new things:)
here's link for video.
https://www.dropbox.com/sh/q48bm0ha7dvr8p8/AADtxl5dny24YR5Dwx3TEnl0a?dl=0

sorry for switching windows many times.
it was hard to bring them how i wanted.

2nd sample played automatically.

**Comment by el-quinto** [comment]
that was good. i can see it is reading the dj krush sample's length correctly when it loads. also looking at the 'coll [mlr]ch 1' window, i can see the sample start/end settings are correct for row 5 (dj krush row)

you're using the most recent group.amxd's from github? this is just so strange, i still can't think of what it might be. even stranger that the issue doesn't happen after u used save+write all and duplicated the set.

**Comment by Hiko-Tanizawa** [comment]
Yes, I just downloaded new zip and put all group,re[mix] and input but still happening ..

**Comment by Hiko-Tanizawa** [comment]
Also option+drag to snap to grid markers mode doesn't work with this version.

**Comment by el-quinto** [comment]
yes i noticed that. fixing it now.

**Comment by el-quinto** [comment]
ok, fixed the snap to grid markers real quick.

**Comment by Hiko-Tanizawa** [comment]
Thank you:)

**Comment by el-quinto** [comment]
the other issue is very hard to figure out. your screenshot/video helped a lot, but it is still really hard to fix without being able to replicate it myself. i'll think about it more over the weekend.

**Comment by Hiko-Tanizawa** [comment]
Thank you so much:)
i just downloaded fixed one but I still can't snap grid .

**Comment by el-quinto** [comment]
apologies. i rushed a bit too much. just a minute.

**Comment by Hiko-Tanizawa** [comment]
No problem.:)
Pls take your time.

**Comment by el-quinto** [comment]
max was crashing every time i tried to save. i had to restart my computer for some reason….

snap to grid is fixed now. i tested before uploading.

**Comment by Hiko-Tanizawa** [comment]
Thank you.
I'm sorry to hear that problems..

**Comment by el-quinto** [comment]
When u load the original set, can u scroll through the max window and see if there's any error messages? (They'll appear with pink color)

**Comment by Hiko-Tanizawa** [comment]
There is one after loaded original set.
![screen shot 2015-03-16 at 7 23 19 pm](https://cloud.githubusercontent.com/assets/11038409/6680274/2042e28c-cc12-11e4-963a-af854d1d55d4.png)

**Comment by Hiko-Tanizawa** [comment]
beginning was like this,
![screen shot 2015-03-16 at 7 23 34 pm](https://cloud.githubusercontent.com/assets/11038409/6680278/39d5ab9e-cc12-11e4-88bf-52e267c4951f.png)

**Comment by Hiko-Tanizawa** [comment]
You are genius.:)
It works fine after i deleted these samples  .

So I guess this happens when re:[mix] can't find samples.

That sample was not able to play on time somehow (slower than original..)so i had to put many different version .

**Comment by Hiko-Tanizawa** [comment]
I just deleted samples,saved and loaded 2 times then both works fine.
Thank you for finding out.

**Comment by el-quinto** [comment]
Cool. Glad we figured it out. I can try to make it so that it won't break a whole set when it can't find a few samples.

**Comment by el-quinto** [comment]
Don't worry about those errors at the beginning btw.

**Comment by Hiko-Tanizawa** [comment]
Thank you very much.:)

I have a question.
Is there way to use fader from mlr_aux app which you sent me last year?

There are 2 vertical rows for effects and 6 vertical rows for faders.

Is there way to make that 6 rows mappable with Ableton?

My64 is correcting dust now.lol
I'm thinking to sell it and buy my own iPad .

**Comment by el-quinto** [comment]
i think maybe u should check out the max audio effect 'multimap' that comes with ableton. u can open it in the max editor and see how it works. (i've never tried, but i think it does what you're looking for)

i just made some latency improvements to the volume mods (at least it seems better for me / no more crazy lag with safari open). :)

let me know if u still get lag.

**Comment by Hiko-Tanizawa** [comment]
Thank you for the info.:)
I just looked inside of Multimap but I could not map with 64 yet.
I will take a look again.

there is no lag any more .
it's so smooth even controlling 6 faders at the same time.:)

**Comment by el-quinto** [comment]
there's a better example called 'multimapper' on the maxforlive website. it's basically the same thing, but 8 knobs instead of one. it doesn't have monome support though. neither does multimap...

if you're looking for a way to make the 6 faders in mlr-aux mappable with Ableton, i was just suggesting these for ideas if you want to try editing mlr-aux.

**Comment by el-quinto** [comment]
i'm thinking about including an example fx rack to demonstrate some things u can do with the per-row macro settings. it seems nobody uses or understands this feature so i thought this might make it easier. what do u think? if u want to try it-

https://dl.dropboxusercontent.com/u/35035949/ex.%20fx.adg.zip

u need to click refresh on group1.amxd once u add it to your group tracks.

**Comment by Hiko-Tanizawa** [comment]
I would like to find out how to use macro efficiently.

**Comment by el-quinto** [comment]
let me know if u need help. the multimapper device i mentioned can be used for re:mix macros if u want. it's really cool because you can map the macros to anything in ableton. (i've had amazing results with it)

**Comment by Hiko-Tanizawa** [comment]
Thank you.
I want to use beat repeat and some effect.
Do you map "macro on/off" ?

**Comment by el-quinto** [comment]
You mean in the setup tab? 

No, that just disables the macro control feature entirely. i thought the option would be useful if u have effect racks on your group tracks and don't want re:mix controlling the macros.

**Comment by Hiko-Tanizawa** [comment]
I see . i kind of finding out little by little.
do you map macro knob in re[mix]?
I mapped them with computer keyboard like on/off each knobs but i need to pick specific row to use it every time.
(maybe i'm using it wrong way.lol)

**Comment by el-quinto** [comment]
no, there isn't a way to toggle on/off macros like with sends because macros are not always as simple as just wet/dry. a macro could be mapped to anything in a rack, so 0 position does not always = dry.

**Comment by el-quinto** [comment]
i'll think about a macro on/off switch, though they weren't really intended to be toggled this way.

**Comment by Hiko-Tanizawa** [comment]
I see.
So how do you use it?
I was thinking to set it manually by keyboard or iPad to change amount and trigger it with monome .

**Comment by el-quinto** [comment]
let's say i want a certain sample with high-pass filter and bit-crush- i set those to controls to the right values in re:mix for the corresponding row, then when i trigger that sample it will have those effects applied. sometimes i'll have the same sample on multiple rows, each with different macro settings to get cool variations.

and this may be obvious, but the 8 knobs in the sampler window next to Sends are your macro settings.

**Comment by Hiko-Tanizawa** [comment]
Now I totally got it.:)
I thought using them on the fly .

That's right .
Many variations with your way to set up.
Thank you so much.:)

**Comment by el-quinto** [comment]
no problem. :)

**Comment by el-quinto** [comment]
i just finished adding a macro toggle switch (check out the readme for new controls)

i'm not going to upload it to github yet because i still might change the controls more over the next couple days.

if u want to try it- https://dl.dropboxusercontent.com/u/35035949/re%5Bmix%5D.zip

**Comment by Hiko-Tanizawa** [comment]
Thank you .:)
I love this one . 
it's very fun.:)

**Comment by Hiko-Tanizawa** [comment]
this one is from read me .

15 (with 12 held) - tap tempo
16 (with 12 held) - macro toggle

15 (with 13 held) - punch-in
16 (with 13 held) - record go

15 (with 12+13 held) - previous recorder input
16 (with 12+13 held) - next recorder input

I think 13 held and 14 held?

**Comment by Hiko-Tanizawa** [comment]
Brightness on 2nd row is slightly weak when held 13+14 together .

![img_7197](https://cloud.githubusercontent.com/assets/11038409/6725914/8d3b7978-cdcd-11e4-9309-03551d14d23c.JPG)

**Comment by el-quinto** [comment]
thats to show you which input is selected.

**Comment by el-quinto** [comment]
yeah 13 & 14. my mistake

**Comment by el-quinto** [comment]
i think i'm going to make the macro on/off switch pattern recordable… i had tried to do a macro on/off switch when i started work on redux but i could never get it to work right. seems pretty good now. :)

i'm going to be rearranging more of the controls with these new mod buttons (preset + - when held) i think i can make switching pages easier now with one hand. (using mod3/4 and the pattern recorders)

**Comment by Hiko-Tanizawa** [comment]
I got it.
Yes please.:)
Thank you so much.

I was able to combine multimap and aux together in one but i think OSC to midi is hard to translate .
I will go with my wife's ipad.lol

**Comment by el-quinto** [comment]
i'm still learning things in max, so every feature i add i have to spend a bunch of time experimenting. for me to make a mappable mlr-aux it would probably take 8+ hours to get it right and bug-free. i know it would be cool, but i don't have a 64 so i would never be able to use it.

**Comment by el-quinto** [comment]
i'm sorry about that. i would help u out if i had a 64.

**Comment by Hiko-Tanizawa** [comment]
oh no problem.:)
I'm really enjoying with this app.
I'm sorry for being delay for video.

**Comment by Hiko-Tanizawa** [comment]
things gets busy nowadays..:(

**Comment by el-quinto** [comment]
this is my key to learning max- wanting a feature bad enough to spend however much free time it takes experimenting to get it working. (most of what i learned is from fixing bugs) lol.

it's why i started redux/re:mix. (because i wanted a functional mlr that bad)

i think making mlr-aux mappable would be a perfect intro to learning max if you ever wanted to start.

**Comment by el-quinto** [comment]
new control layout. pattern recordable macro switch :)

https://dl.dropboxusercontent.com/u/35035949/re%5Bmix%5Db.zip

**Comment by Hiko-Tanizawa** [comment]
YES!!
I just tried little bit and it's very good .:)
I can't wait to play around tonight.

**Comment by Hiko-Tanizawa** [comment]
Thank you so much.:)

**Comment by Hiko-Tanizawa** [comment]
Yey more control on monome.:)
I have an idea.
how about switch like this ?
15 (with mod 3 held)    set tempo (light indicates a mismatch between current and preset tempos)

15 - macro toggle (can be momentary when held) (pattern recordable)

I caught myself changing presets by accidentally when using macro control and  I assume ppl use it more than changing tempo?

It's just an idea :)
let me know what you think.

also In record length mode press 9 does not have light on.

**Comment by el-quinto** [comment]
9 is sort of a weird record length anyways, so i wouldn't worry about it so much. i took the record length page code from mlr_cyst and knew about that bug too.

**Comment by el-quinto** [comment]
i was thinking the same thing. :) i made macro toggle button 15, and record go is now mod3+4 pressed together

**Comment by Hiko-Tanizawa** [comment]
Thank you.
I'm having fun with it.:)
