### ISSUE TITLE
Problem with ext. input

### ISSUE THREAD

**Issue by Holl1f3ld** [el-quinto/mix#8]
hello sir,

having an issue with ext. input not being recorded into the buffer.  live9 max7 win7.  

input.amxd recieves signal though im not sure what else to try.  respect.

**Comment by el-quinto** [comment]
are the 1-8 switches on the input.amxd all off maybe? light grey is on.

**Comment by Holl1f3ld** [comment]
By default they are "on", but in any event i toggled and fiddled to no avail.

**Comment by el-quinto** [comment]
weird. recording has always worked for me on osx.

is the track's monitoring set to Off? is the transport not running? those are the only other things i can think of that would prevent it from recording.

**Comment by el-quinto** [comment]
Ok, i installed Ableton/max on my windows partition and every time i try to record it crashes Live. Not sure what's going on right now.

**Comment by el-quinto** [comment]
i found/fixed the source of the crashes, then recording was working consistently (windows 7, Live 9.1.8, max 6.1.10)

when u get the chance, try out the latest build and let me know if its working now.

**Comment by el-quinto** [comment]
btw i wouldn't recommend using it with max 7 yet…  i've been developing it with max 6 (waiting for Live 9.2, where you don't need a max 7 license to use it with m4l anymore.)

**Comment by Holl1f3ld** [comment]
So all is working smoothly now.  Ur a legend!

**Comment by el-quinto** [comment]
good to hear
